apiVersion: v1
kind: Service
metadata:
    name: "helloapp"
    labels:
        app: helloapp
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: aks-mydigitalthread
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloapp
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: aks-mydigitalthread-2f81d1a9.hcp.eastus.azmk8s.io
    http:
      paths:
       - path: /hello
         backend:
          serviceName: helloapp
          servicePort: 80
          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp
  labels:
    app: helloapp
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      name: helloapp
      labels:
        app: helloapp
    spec:
      containers:
        - name: helloapp
          image:  adopcontainerregistry.azurecr.io/hello-world
          ports:
           - containerPort: 8080
  selector:
    matchLabels:
      app: helloapp
